# Generated by Django 3.0 on 2019-12-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vp', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('pu', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('klass', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('adress', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('count_ls', models.IntegerField(blank=True, default=None, null=True)),
                ('mp', models.IntegerField(blank=True, default=None, null=True)),
                ('sbol', models.IntegerField(blank=True, default=None, null=True)),
                ('ap', models.IntegerField(blank=True, default=None, null=True)),
                ('us', models.IntegerField(blank=True, default=None, null=True)),
                ('vsp', models.IntegerField(blank=True, default=None, null=True)),
                ('count_pay', models.IntegerField(blank=True, default=None, null=True)),
                ('share_of_pay_mp', models.FloatField(blank=True, default=None, null=True)),
                ('share_of_pay_sbol', models.FloatField(blank=True, default=None, null=True)),
                ('share_of_pay_ap', models.FloatField(blank=True, default=None, null=True)),
                ('share_of_pay_us', models.FloatField(blank=True, default=None, null=True)),
                ('share_of_pay_vsp', models.FloatField(blank=True, default=None, null=True)),
                ('region', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('tb', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
    ]
