# Generated by Django 3.0 on 2019-12-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geopoint',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
